

//Greeting

console.log("welcome to Game One\n");

//Readline constructor

const readline = require("readline").createInterface({
input: process.stdin,
output: process.stdout
});

//Main function 

function handleUserResponse (response){

    let userResponse = validateUserResponse(response);

    let robotsChoice = randomComputerOutput(); 

    if(userResponse) {

        console.log("Hey Human I have chosen: " + robotsChoice + "\n" + "R2-D2 I have shosen: " + userResponse + "\n");

        findWinner(robotsChoice, userResponse);
        readline.close();
        
    } else {
        console.log(userResponse);
        readline.question("WRONG!!!\nPlease choose either rock, paper or scissors!\n", handleUserResponse);
    
    }

}

//Program Trigger

readline.question("Please choose either rock, paper or scissors! \n", handleUserResponse);

//Cmputer answer generated by transforming randomly generated number to a valid string

function randomComputerOutput() {

    let randomNum = (Math.floor(Math.random() * 3) + 1);

    if (randomNum == 1) {

        return "Rock";

    } else if (randomNum == 2) {

        return "Scissors";

    } else return "Paper";
}

//User input validation

function validateUserResponse(userInput) {

    let options = ["Rock", "Paper", "Scissors"];
    let result;

    for(let el of options) {
        el.toLowerCase() === userInput.toLowerCase() ? result = el : false;
    }
    return result;
}

//The function compare user's and computer's answers

function findWinner(robotAnswer, humanAnswer) {

    if(robotAnswer == humanAnswer) {
        console.log("We are Even Human!");
    } else if(robotAnswer == "Rock" && humanAnswer == "Paper") {
        console.log("HUMAN +1");
    }else if(robotAnswer == "Paper" && humanAnswer == "Scissors") {
        console.log("HUMAN +1");
    }else if(robotAnswer == "Scissors" && humanAnswer == "Rock") {
        console.log("HUMAN +1");
    }else console.log("ROBOT +1");

}